apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: spotinstances.example.com
spec:
  group: example.com
  names:
    kind: SpotInstance
    listKind: SpotInstanceList
    plural: spotinstances
    singular: spotinstance
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instanceType:
                  type: string
                price:
                  type: string
                availabilityZone:
                  type: string
